### ISSUE TITLE
KITTI dataset

### ISSUE THREAD

**Issue by Wansit99** [liuQuan98/GCL#3]
Could you please provide a detailed description of how to use the KITTI dataset? Why are the labels and dataset both under the sequence folder after I unzip it?

**Comment by Wansit99** [comment]
thank for your great work,I got it!But why the training is so slowly?

**Comment by Wansit99** [comment]
11/14 09:45:16 Train Epoch: 1 [0/278], Current Loss: 1.213e+00 Pos: 0.254 Neg: 0.780 Finest: 0.179      Data time: 20.3755, Train time: 2.3035, Iter time: 22.6790
11/14 09:55:22 Train Epoch: 1 [40/278], Current Loss: 9.915e-01 Pos: 0.176 Neg: 0.761 Finest: 0.054     Data time: 12.5705, Train time: 2.5699, Iter time: 15.1404

about 70 mins a epoch(sad)

**Comment by liuQuan98** [comment]
> 11/14 09:45:16 Train Epoch: 1 [0/278], Current Loss: 1.213e+00 Pos: 0.254 Neg: 0.780 Finest: 0.179 Data time: 20.3755, Train time: 2.3035, Iter time: 22.6790 11/14 09:55:22 Train Epoch: 1 [40/278], Current Loss: 9.915e-01 Pos: 0.176 Neg: 0.761 Finest: 0.054 Data time: 12.5705, Train time: 2.5699, Iter time: 15.1404
> 
> about 70 mins a epoch(sad)

As you can see, the training time is largely occupied by the data loading threads. Take a closer look and you will find it mainly made up of the nearest-neighbor search process, as we will need to exhaustively search neighbors across 7 point clouds under the default setting which is pretty slow.

On my workstation, GCL runs an epoch in around 35 minutes. Surely the search requires CPU capabilities and may not be transferable to others' workstations. Luckily, there should be easy fixes to tune down this cost as follows.

Recommendations: 
1. (Optional, degrades performance) Turn down `--num_neighborhood` to 4
2. Downsample the number of query points in the previously mentioned nearest-neighbor search step. However, this will require some further testing to reveal currently unknown performance-wise implications. It is located [here](https://github.com/liuQuan98/GCL/tree/main/util/pointcloud.py) in line 69. A simple yet not elegant fix would be to replace line 92 with this:
```
  central_indices = np.random.choice(len(central_xyz), 5000, replace=False)
  for i, point in enumerate(central_xyz):
    if i not in central_indices:
      continue
```
I might not be able to test this so soon so feel free to share your feedback here.

**Comment by liuQuan98** [comment]
I was surely being dizzy when I first answered this question. Bumping 'train_num_thread' up significantly would obliterate any extra time spent on dataloader threads as long as your CPU can handle the cost.
